### ISSUE TITLE
Test 205 (Non-secure SGIs are implemented) shouldn't check invalid PE cores

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#102]
Test currently not checking the correct base address of GIC RD of a PE.

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm,

Bug fix for the issue is raised https://github.com/ARM-software/bsa-acs/pull/109. The changes are under verification and PR will be merged once verified.

Thanks,
ACS team

**Comment by sunnywang-arm** [comment]
Verified the fix. It worked fine, so closed the issue.

**Comment by sunnywang-arm** [comment]
Reopen it to wait for merging.

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm, 

Thanks for helping in the verification of the fix, the changes are merged.
