### ISSUE TITLE
PCIe tests can't be run when the PCIe root port is hidden by firmware

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#112]
We got the error message below on a platform and then all PCIe tests got skipped. 
- `PCIe Hierarchy fail: RP of bdf 0x4010000 not found Create Bdf table failed.`

Although the PCIe root ports on this platform are hidden by firmware, we should still run PCIe tests for the end-point devices. In other words, It is better to see that the PCIe Hierarchy problem causes the FAILED or SKIPPED results with some PCIe tests instead of having an error message during the initialization and no test failure.

**Comment by gowthamsiddarthd** [comment]
Hi @sunnywang-arm,

Thank you for reporting this. As suggested, whenever the test encounters an EP without an assigned RP, the system will report error. Simultaneously, the test will continue its execution without interruption, progressing with the evaluation of other tests as usual. By implementing this change, we can maintain the overall efficiency of our testing operations while proactively addressing any incomplete or missing information.

Regards,
Gowtham
