### ISSUE TITLE
ITS test 003 Issue

### ISSUE THREAD

**Issue by ndhillonm** [ARM-software/bsa-acs#17]
Hey Guys,
Can you please look at the "test_os_its003.c" ?
In particular, the array 'streamID' which is 32 elements long but it is updated using 'dev_index' variable which clearly goes past 32 if there are enough 'bdf_tbl_ptr->num_entries'.
This causes memory corruption.

Thanks,
Narinder

**Comment by chetan-rathore** [comment]
Hi @ndhillonm,

The fix for the issue has been upstreamed.

Thanks,
ACS team
