### ISSUE TITLE
test_os_p030.c

### ISSUE THREAD

**Issue by ndhillonm** [ARM-software/bsa-acs#21]
In the 'esr' function of this test, ELR register is being set to an instruction to jump to. It is not working for me and I am wondering if this is a bug.
Current instruction is as follows but results in a hang in our system.
"val_pe_update_elr(context, (uint64_t)branch_to_test);"

To get around this, "val_pe_update_elr(context, (uint64_t)(((EFI_SYSTEM_CONTEXT_AARCH64*)context)->ELR + 4));", seems to behave better.

Is this a real issue or is it just our SoC ?

Thanks,

**Comment by ndhillonm** [comment]
Hi Chetan,

Log attached. Hope you receive it.

Thanks,
Narinder

From: chetan singh rathore ***@***.***>
Sent: Thursday, February 24, 2022 7:20 AM
To: ARM-software/bsa-acs ***@***.***>
Cc: Narinder Dhillon ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [ARM-software/bsa-acs] test_os_p030.c (Issue #21)

External Email
________________________________

Hi @ndhillonm<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ndhillonm&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=qnkNXnESac38p9pJw3epqv4z8rcQK5CWd_frG7JiOC0KONWFvtA4kg-3SZW6sHw3&s=ra65t6zZQDhp40UowR75fr2_ONkG32YHcX0wy-sYysg&e=>,

The "branch_to_test" is set to jump to the desired location in the test after handling the exception. val_pe_update_elr function updates the ELR register to the offset pointed by branch_to_test.

Can you please share debug logs with this binary to debug the issue further: https://github.com/chetan-rathore/bsa-acs/blob/main/prebuilt_images/Bsa_430.efi<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chetan-2Drathore_bsa-2Dacs_blob_main_prebuilt-5Fimages_Bsa-5F430.efi&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=qnkNXnESac38p9pJw3epqv4z8rcQK5CWd_frG7JiOC0KONWFvtA4kg-3SZW6sHw3&s=aE2DVxas_NPdoAtVl-y1gT8QRQ0yIUNJRTtOOQMhJgc&e=>

We have added prints to check branch_to_test offset value in payload and esr function.

Thanks!!

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ARM-2Dsoftware_bsa-2Dacs_issues_21-23issuecomment-2D1049966926&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=qnkNXnESac38p9pJw3epqv4z8rcQK5CWd_frG7JiOC0KONWFvtA4kg-3SZW6sHw3&s=2L4w6_NikVoCksqU4CaQZFveQl-eajvjePSSOfrVKk4&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AWA5AVCY3X4PWGX4XRCBGPTU4ZECXANCNFSM5NU54DHQ&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=qnkNXnESac38p9pJw3epqv4z8rcQK5CWd_frG7JiOC0KONWFvtA4kg-3SZW6sHw3&s=pOIEBKDEYbhYNJweZKp8syWvniDyIb9eqcQz8vVkyOQ&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=qnkNXnESac38p9pJw3epqv4z8rcQK5CWd_frG7JiOC0KONWFvtA4kg-3SZW6sHw3&s=hey_riThSgOBMHs3N9zcdjzlofUQdJlKsTfFi0nSHJI&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=qnkNXnESac38p9pJw3epqv4z8rcQK5CWd_frG7JiOC0KONWFvtA4kg-3SZW6sHw3&s=WJA1mxhgTAgJXJ3KVpmj0uqfa3cqXi-wq78_aSAqCmE&e=>.

**Comment by chetan-rathore** [comment]
Hi @ndhillonm, 

Unfortunately, didn't receive the logs on the github account email id.
Can you please send the logs to chetan.rathore@arm.com

Thanks!!

**Comment by ndhillonm** [comment]
Sent.

From: chetan singh rathore ***@***.***>
Sent: Wednesday, March 2, 2022 3:38 AM
To: ARM-software/bsa-acs ***@***.***>
Cc: Narinder Dhillon ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [ARM-software/bsa-acs] test_os_p030.c (Issue #21)

External Email
________________________________

Hi @ndhillonm<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ndhillonm&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=uiMZNUHnPwzXKU17ddRySFV14pHtfm2Y_m7g6RXpp98_tBcxBx2PVpZ-5nguop3e&s=xGAPZyzRvr5-SldnVwcmCTLMDfgLLhzpsrvqTtb1lkU&e=>,

Unfortunately, didn't receive the logs on the github account email id.
Can you please send the logs to ***@***.******@***.***>

Thanks!!

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ARM-2Dsoftware_bsa-2Dacs_issues_21-23issuecomment-2D1056831779&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=uiMZNUHnPwzXKU17ddRySFV14pHtfm2Y_m7g6RXpp98_tBcxBx2PVpZ-5nguop3e&s=kbgX-8s4ANfxekUhst0npv6GUBIJBUT6A37k49vrYRc&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AWA5AVAJOWF3ZUPNPFAQEOTU55HJHANCNFSM5NU54DHQ&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=uiMZNUHnPwzXKU17ddRySFV14pHtfm2Y_m7g6RXpp98_tBcxBx2PVpZ-5nguop3e&s=qX5mnn9e1yiVxV9w2ey1wiI3PPI8zeRYdCM9JTcNU0o&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=uiMZNUHnPwzXKU17ddRySFV14pHtfm2Y_m7g6RXpp98_tBcxBx2PVpZ-5nguop3e&s=bsVBldDgZTX9Ek2xaRmctkIVvWuG-b-nwF8Cre6lSAs&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=nKjWec2b6R0mOyPaz7xtfQ&r=1o2VA7xKsHvmQ4HFRY2JZggF-gGh1t4bxHFABsB1WTo&m=uiMZNUHnPwzXKU17ddRySFV14pHtfm2Y_m7g6RXpp98_tBcxBx2PVpZ-5nguop3e&s=w6M8tmlz-q6mpSNwRFnv5TSMBIQ_fYVJ9v9wEcC6q8o&e=>.

**Comment by chetan-rathore** [comment]
Hi @ndhillonm,

Thanks for the logs.

From the test 830 prints, val_pe_update_elr is working correctly.
All the PCIe tests have also been completed.

On the failure of test 830 in the logs, it seems the root port URD (unsupported request detected) bit is not getting set.

As per PCIe spec,
Memory Space Enable - Controls a Function's response to Memory Space accesses. **When this bit is
Clear, all received Memory Space accesses are caused to be handled as Unsupported Requests.** When
this bit is Set, the Function is enabled to decode the address and further process Memory Space

**Comment by chetan-rathore** [comment]
Hi @ndhillonm, 

Please reopen the ticket, if the issue is observed again.
