### ISSUE TITLE
Can spaces/tabs be consistent?

### ISSUE THREAD

**Issue by hrw** [ARM-software/bsa-acs#231]
As part of my work on SBSA Reference Platform in QEMU I am running (S)BSA ACS ~weekly. And amount of space related changes suggests low review quality inside Arm.

Can you get spaces/tabs to be consistent? And then keep it? Do some CI runs on internal review and expose differences in output compared to previous version.

![image](https://github.com/ARM-software/bsa-acs/assets/185508/1b41f787-4c83-4bb7-9492-9a3d443c6c1a)

**Comment by chetan-rathore** [comment]
Hi @hrw,

Thanks for raising the issue.

We will take the feedback and remove the end of line spaces and also include same in CI.
Please note the test description uses max 70 character and in cases where the test description is not filling all 70 characters..spaces are used.

Can you please also pass the logs where the "ECAM base is zero " is coming.

Thanks,
ACS team

**Comment by hrw** [comment]
https://github.com/hrw/sbsa-ref-status/ has all my logs.

Will check tomorrow are they up to date.

**Comment by hrw** [comment]
There is also a script I use to gather logs.

**Comment by hrw** [comment]
updated logs

**Comment by chetan-rathore** [comment]
Hello @hrw,

We've made changes to eliminate trailing spaces at the end of lines, the numbers of files affected are 54 files. Since these modifications are related to a single issue, our intention is to consolidate them into a single pull request.

Thanks,
ACS team

**Comment by hrw** [comment]
https://github.com/hrw/sbsa-ref-status/commit/344b8a35a21a7782237aa59b8880b4d0bbe5cd40 shows how it changed (fresh ACS logs)

**Comment by hrw** [comment]
```
 501 : Wake from EL1 PHY Timer Int           
       START       Received EL1 PHY interrupt

       B_WAK_01, B_WAK_02, B_WAK_03, B_WAK_04, B_WAK_05                     HERE
       B_WAK_06, B_WAK_07, B_WAK_10, B_WAK_11
                                       : Result:  PASS
       END
```

"HERE" shows where extra spaces were left.
