### ISSUE TITLE
[Regression] Missing patch from PR-265 in sbsa-acs repository. pal_pe.c uses bad stack alignment.

### ISSUE THREAD

**Issue by r0bwoo** [ARM-software/bsa-acs#239]
PE tests crash on GCE machines due to a stack alignment issue with stack allocation. This issue was fixed before but didn't seem to make the move to this testing suite. PR in question that should be propagated is as follows:

https://github.com/ARM-software/sbsa-acs/pull/265

**Comment by chetan-rathore** [comment]
Hello @r0bwoo ,

Thanks for highlighting the PR for the issue.
We are planning to update bsa-acs with the required changes by this week.

Thanks,
ACS team

**Comment by chetan-rathore** [comment]
Hello @r0bwoo,

Required changes are merged in the ACS.

Thanks,
ACS team
