### ISSUE TITLE
Linux drive's IOVIRT_INFO_TBL_SZ is not aligned app's value

### ISSUE THREAD

**Issue by foxmmmm** [ARM-software/bsa-acs#248]
IOVIRT_INFO_TBL_SZ  value (32768) in Linux drive bsa_acs_drv.h/sbsa_acs_drv.h are not equal  uefi_app/BsaAcs.h/SbsaAvs.h value(1048576), they should be the same value.

**Comment by chetan-rathore** [comment]
Hello @foxmmmm,

We are looking into the issue and will share the updates soon.

Thanks,
ACS team

**Comment by chetan-rathore** [comment]
Hello @foxmmmm,

Changes of the issue are merged in linux-acs. https://gitlab.arm.com/linux-arm/linux-acs/-/merge_requests/4

Thanks,
ACS team
