### ISSUE TITLE
Check for PMUv3 support before reading registers

### ISSUE THREAD

**Issue by r0bwoo** [ARM-software/bsa-acs#249]
One of the patches from the original SBSA test did not seem to propagate to this test which was a pre-check for PMUv3 registers before testing. Assuming these registers existed created issues with PE testing where tests will fail and the message " PSCI_CPU_ON: cpu already on" will print. The PR that was submitted and merged in can be found here:

https://github.com/ARM-software/sbsa-acs/pull/266

These changes cannot be seen in bsa-acs/test_pool/pe/operating_system/test_os_c001.c in the register details list and should be imported here as well to fix this issue.

**Comment by rajatgoyal47** [comment]
Thanks @r0bwoo for the reporting this.

Agree that before accessing the Performance Monitors registers, check for PMUv3 feature should be made.
We will upstream the changes soon.

Best Regards,
ACS Team
