### ISSUE TITLE
Confusing error messages from test 822  

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#255]
```
822 : Check Type 1 config header rules 
- BDF 0x100 : SLT attribute mismatch: 0xFF010100 instead of 0x10100
```

The test checks the bit 0 to 7 from offset 0x1B (0x18 + 3), but the message shows the bit 0 to 31 from offset 0x18. 

Can we make the change below to https://github.com/ARM-software/bsa-acs/blob/08ea31284b0692fa9ccc648dacb443e9e2e5115c/test_pool/pcie/operating_system/test_os_p022_data.h or update the messages?
       ~~0x1B,                                    // Offset from ECAM base~~
       0x18,                                    // Offset from ECAM base
       RP,                                      // Applicable to Rootports
      ~~0,                                       // Start bit position~~
       24,                                       // Start bit position
       ~~7,                                       // End bit position~~
       31,                                       // End bit position

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm,

Thanks for raising this. We have modified the print message to output only the value of BITS under test.

Snippet:
 822 : Check Type 1 config header rules
       BDF 0x300 : SLT attribute mismatch: 0xFF instead of 0x0
       BDF 0x400 : SLT attribute mismatch: 0xFF instead of 0x0
       BDF 0x500 : SLT attribute mismatch: 0xFF instead of 0x0
       BDF 0x600 : SLT attribute mismatch: 0xFF instead of 0x0
       BDF 0x700 : SLT attribute mismatch: 0xFF instead of 0x0
       BDF 0x800 : SLT attribute mismatch: 0xFF instead of 0x0
       BDF 0x10000 : SLT attribute mismatch: 0xFF instead of 0x0
