### ISSUE TITLE
Update test 863 "PCI legacy intr SPI ID unique" to print out more information for identifying problemaic device

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#264]
https://github.com/ARM-software/bsa-acs/blob/main/test_pool/pcie/operating_system/test_os_p063.c

Now the failure message only shows the following two lines, which is not enough for us to identify problematic devices. Can we also print out the BDF number and IRQ/SPI ID number? 
```
 863 : PCI legacy intr SPI ID unique         
     Legacy interrupt A routing
     is the same as B routing
     Failed on PE -    0
     Checkpoint --  7                           : Result:  FAIL 
```

**Comment by gowthamsiddarthd** [comment]
This enhancement has been provided by the PR https://github.com/ARM-software/bsa-acs/pull/271
