### ISSUE TITLE
Features not supported causes test item to fail

### ISSUE THREAD

**Issue by hysen0523** [ARM-software/bsa-acs#270]
Test item in BSA "6. Check Cryptographic extensions" failed. The root cause is that bits 7:4, 11:8, 15:12 of ID_AA64ISAR0_EL1 are all zeros. Should this test case be waived? Or, update this test case to get a "skip" result if FEAT_AES/FEAT_SHA1/FEAT_SHA256 not supported? Or other solutions? Thanks a lot.

<img width="599" alt="image" src="https://github.com/ARM-software/sbsa-acs/assets/41116023/43ec0252-9168-4d27-8d56-3df9c952d897">

**Comment by chetan-rathore** [comment]
Hello @hysen0523, 

Test will be updated in same manner as similar SBSA test ad described in https://github.com/ARM-software/sbsa-acs/issues/439

Thanks,
ACS team
