### ISSUE TITLE
Add few more prints to PE test 1 (Check Arch symmetry across PE) 

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#303]
We want to know the inconsistent value of PE registers for debugging. However, now the message only shows the masked out value. 

For verbosity message, add few prints to show values of registers right after the line https://github.com/ARM-software/bsa-acs/blob/main/test_pool/pe/operating_system/test_os_c001.c#L172.

For default mesasge, add prints right before the line https://github.com/ARM-software/bsa-acs/blob/main/test_pool/pe/operating_system/test_os_c001.c#L174.

**Comment by sunnywang-arm** [comment]
Chetan found an issue with line https://github.com/ARM-software/bsa-acs/blob/main/test_pool/pe/operating_system/test_os_c001.c#L248 while checking this improvement. The correct value is held by cache_list and not by rd_data_array so the message "Current PE value = xxxxxxxxxx" could be misleading. 


For adding prints, Test 1 is multi-PE test, but On EDK2/UEFI you can’t use any protocols to print message on secondary PEs as the code is not MP safe. Therefore, ACS team will look into the solution that make the memory buffer bigger and save values from all PEs then print them all in the primary PE.

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm,

ACS team is working on the changes and will upstream the changes soon.

Thanks,
ACS team
