### ISSUE TITLE
PE test 1 should continue checking all PE registers in reg_list after finding an failure 

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#304]
Now PE test 1 (Check Arch symmetry across PE) directly returns once it finds a inconsistent value of PE registers in cores.  The test should continue checking other PE registers as we want to identify all the issues. 
https://github.com/ARM-software/bsa-acs/blob/main/test_pool/pe/operating_system/test_os_c001.c#L176

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm,

ACS team is working on the changes and will upstream the changes soon.

Thanks,
ACS team
