### ISSUE TITLE
PE test 1 doesn't check last few PE registers in reg_list[]

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#308]
The value of NUM_OF_REGISTERS should be updated to match the number of registers in reg_list []. There are more than 32 registers in reg_list[]. 
https://github.com/ARM-software/bsa-acs/blob/8d2382ad2be86ee2598dc69703e11c9315c3cf2b/test_pool/pe/operating_system/test_os_c001.c#L25

**Comment by magicse7en** [comment]
some register reads are commented out, which should also be updated.
https://github.com/ARM-software/bsa-acs/blob/main/val/common/src/AArch64/PeRegSysSupport.S#L394C9-L394C23

**Comment by sunnywang-arm** [comment]
Thanks for the feedback, @hrw and @magicse7en. Agree with your comments. I created another task to update the list. 
https://github.com/ARM-software/bsa-acs/issues/318

**Comment by chetan-rathore** [comment]
PR #342 has enabled further 5 registers which were mentioned in test case, but were either commented out or not executing due to lesser value of NUM_OF_REGITER.

**Comment by sunnywang-arm** [comment]
Thanks, @chetan-rathore. Closing the issue as it got fixed by PR https://github.com/ARM-software/bsa-acs/pull/342.

**Comment by hrw** [comment]
Please add ID_AA64MMFR3_EL1 register. We got cpu which has Spec_FPACC bits set.
