### ISSUE TITLE
How to poweron other pe with psci smc to run test

### ISSUE THREAD

**Issue by LaughingLeeLife** [ARM-software/bsa-acs#326]
![image](https://github.com/user-attachments/assets/91b9720b-e0ba-42de-8079-82d0ff778bfc)

BSA with baremetal.
My HW platform has 12cores and bootup by core4.
I not sure how to power on other pe with psci smc to run pe test. Because smc will go into the default handler.
I still meet this issue even I poweron all cores with core4 at the same time by system control unit.

![image](https://github.com/user-attachments/assets/831409d3-379e-45e4-b2b0-26fc519bab18)

**Comment by rajatgoyal47** [comment]
Hi,

FAR (Fault Address Register) in the snapshot is 0x0, which means code is trying to access address 0x0 resulting into Unexpected exception.
Request you to share the complete log file, as it would help in further looking into the issue you are facing. 

In addition, Please note that running the BSA with BM would require the platform config details at
https://github.com/ARM-software/bsa-acs/blob/main/pal/baremetal/target/RDN2/common/src/platform_cfg_fvp.c
to be populated correctly.

Please ensure the required details are populated correctly. For more information on how to populate the data please refer
https://github.com/ARM-software/bsa-acs/blob/main/docs/arm_bsa_architecture_compliance_bare-metal_user_guide.pdf
.

Regards,
ACS Team

**Comment by chetan-rathore** [comment]
Hi @LaughingLeeLife,

Please let us know if you have any further queries or this ticket can be closed.

Thanks,
ACS team
