### ISSUE TITLE
Test 1 is oververbose

### ISSUE THREAD

**Issue by hrw** [ARM-software/bsa-acs#340]
Looks like someone forgot to switch loglevel for some prints:

```
      *** Starting PE tests ***

Operating System View:
   1 : Check Arch symmetry across PE
Primary PE Index : 0, MIDR_EL1 : 0x00000000410FD493
        PE Index : 1, MIDR_EL1 : 0x00000000410FD493
        PE Index : 2, MIDR_EL1 : 0x00000000410FD493
        PE Index : 3, MIDR_EL1 : 0x00000000410FD493     : Result:  PASS
   2 : Check for number of PE                     : Result:  PASS
```

**Comment by hrw** [comment]
Maybe cpu info should be a part of information block then? Next to gic, smmu, pcie etc.

**Comment by hrw** [comment]
Kind of (MIDR_EL1 as 32-bit cause top 32 ones are reserved):

```
 Creating Platform Information Tables
 PE_INFO: Number of PE detected       :    4
 Primary PE Index : 0, MIDR_EL1       :    0x410FD493
         PE Index : 1, MIDR_EL1       :    0x410FD493
         PE Index : 2, MIDR_EL1       :    0x410FD493
         PE Index : 3, MIDR_EL1       :    0x410FD493
 GIC INFO: GIC version                :    v3
 GIC_INFO: Number of GICD             :    1
 GIC_INFO: Number of GICR RD          :    1
 GIC_INFO: Number of ITS              :    1
 TIMER_INFO: System Counter frequency :    0x3B9ACA00
 TIMER_INFO: Number of system timers  :    0
 WATCHDOG_INFO: Number of Watchdogs   :    1
 PCIE_INFO: Number of ECAM regions    :    1
 PCIE_INFO: Number of BDFs found      :    4
 PCIE_INFO: Number of RCiEP           :    2
 PCIE_INFO: Number of RCEC            :    0
 PCIE_INFO: Number of EP              :    1
 PCIE_INFO: Number of RP              :    1
 PCIE_INFO: Number of iEP_EP          :    0
 PCIE_INFO: Number of iEP_RP          :    0
 PCIE_INFO: Number of UP of switch    :    0
 PCIE_INFO: Number of DP of switch    :    0
 PCIE_INFO: Number of PCI/PCIe Bridge :    0
 PCIE_INFO: Number of PCIe/PCI Bridge :    0
 SMMU_INFO: Number of SMMU CTRL       :    1
 SMMU_INFO: SMMU index 00 version     :    v3.1
 Peripheral: Num of USB controllers   :    1
 Peripheral: Num of SATA controllers  :    1
 Peripheral: Num of UART controllers  :    1
```

This way cpu information would be part of information block nevermind which tests are run.

**Comment by sunnywang-arm** [comment]
Yeah, that is a good idea.

**Comment by chetan-rathore** [comment]
Hi @hrw and @sunnywang-arm,

The MIDR values will be mostly used when debugging PE test 1, so it makes sense to have it in Test-1.
We can move the prints to DEBUG level, so in case when running on System with high number of cores (> 100), the default logs doesn't get over verbose.

Please let us know your inputs.

Thanks,
ACS team

**Comment by hrw** [comment]
When you have tens, hundreds of cores then they mostly are of one kind. Mix is mostly in mobile chips where you have up to 8 cores total.

Also there can be code which would print by default (values random):

```
 Creating Platform Information Tables
 PE_INFO: Number of PE detected       :    4
 Primary PE Index : 0, MIDR_EL1       :    0x410FD493
         also seen cores              :    0x410FD483, 0x410FD403
 GIC INFO: GIC version                :    v3

```

With values for each core printed on debug level.

**Comment by sunnywang-arm** [comment]
> Also there can be code which would print by default (values random):
> 
> ```
>  Creating Platform Information Tables
>  PE_INFO: Number of PE detected       :    4
>  Primary PE Index : 0, MIDR_EL1       :    0x410FD493
>          also seen cores              :    0x410FD483, 0x410FD403
>  GIC INFO: GIC version                :    v3
> ```
> 
> With values for each core printed on debug level.

Marcin's proposal above is good, but I also agree with Chatan's comment that "The MIDR values will be mostly used when debugging PE test 1, so it makes sense to have it in Test-1". It might NOT be worth adding code to print out the non-primary PE MIDR value in the information block.    

So how about we do the following:
In the information block, we only print primary PE MIDR value
 ```
  Creating Platform Information Tables
  PE_INFO: Number of PE detected       :    4
  Primary PE Index : 0, MIDR_EL1       :    0x410FD493
  GIC INFO: GIC version                :    v3
```
In test-1, 
- By default, Print different core's MIDR when a different MIDR value is detected. 
- On Debug level, Print each core's MIDR value.

**Comment by hrw** [comment]
Sounds good to me.

**Comment by hrw** [comment]
Nice

```
 Creating Platform Information Tables
 PE_INFO: Number of PE detected       :    4
 Primary PE: MIDR_EL1                 :    0x410FD493
 GIC INFO: GIC version                :    v3
```

```
Operating System View:
   1 : Check Arch symmetry across PE
       Primary PE Index : 0, MIDR_EL1 : 0x410FD493
       Other Cores :  Identical
     : Result:  PASS
   2 : Check for number of PE                     : Result:  PASS
```

But can "Result: PASS" be aligned to other results?
