### ISSUE TITLE
Plans for BSA ACS v1.0.9?

### ISSUE THREAD

**Issue by ricardosalveti** [ARM-software/bsa-acs#369]
https://github.com/ARM-software/bsa-acs/releases/tag/v24.03_REL1.0.8 was last released in march, are there any plans for a 1.0.9 release?

Thanks!

**Comment by chetan-rathore** [comment]
Hi @ricardosalveti,

Yes the next BSA and SBSA release are planned around mid-November.

Thanks,
ACS team

**Comment by ricardosalveti** [comment]
Great, thanks for the quick answer.
