### ISSUE TITLE
Latest ACS tip build is causing error on SIE TC

### ISSUE THREAD

**Issue by quic-pansing** [ARM-software/bsa-acs#400]
We have compiled latest ARM tip and compiled. When we are trying with tip build with ACS keys we are observing keys getting updated and not getting original values . So during next boot image authentication/verification failed. So we are unable to launch grub menu to get report. 
But with Prebuild and ACS keys we are able to generate report.

**Comment by chetan-rathore** [comment]
Hi @quic-pansing,

With the latest arm-systemready tip, the BBSR issue is resolved.

Thanks,
Chetan

**Comment by quic-pansing** [comment]
we see still issue.
