### ISSUE TITLE
Release v24.11_REL1.0.9   indentation error

### ISSUE THREAD

**Issue by quic-pansing** [ARM-software/bsa-acs#405]
line 352 : indentation error:
https://github.com/ARM-software/arm-systemready/blob/main/common/log_parser/apply_waivers.py

Log:

[   55.338703] init.sh[375]:   Waiver File        : /mnt/acs_tests/config/acs_waiver.json
[   55.697604] init.sh[381]:   File "/usr/bin/log_parser/apply_waivers.py", line 353
[   55.697811] init.sh[381]:     output_json_data = None

**Comment by ricardosalveti** [comment]
Please propose a patch with the fix.

**Comment by chetan-rathore** [comment]
Hi @ricardosalveti and @quic-pansing,

We will be upstreaming the fix for the issue by eod.

Thanks,
Chetan

**Comment by chetan-rathore** [comment]
The changes for the fix is merged in arm-systemready repo: https://github.com/ARM-software/arm-systemready/pull/235
