### ISSUE TITLE
Release v24.11_REL1.0.9  acs_waiver.json missing.

### ISSUE THREAD

**Issue by quic-pansing** [ARM-software/bsa-acs#409]
acs_waiver.json sample file is needed.

**Comment by chetan-rathore** [comment]
Hi @quic-pansing,

We are working on it and will share the sample waiver json and guidelines to apply it by today.

Thanks,
Chetan

**Comment by chetan-rathore** [comment]
Hi @quic-pansing,

The sample waiver json and guide on details of waiver application process are documented here: https://github.com/ARM-software/arm-systemready/tree/main/common/docs

1. example_waiver.json
2. waiver_guide.md

Thanks,
Chetan
