### ISSUE TITLE
Test case 606 UART loopback test doesn't mask off MSR delta bits

### ISSUE THREAD

**Issue by hnickvmw** [ARM-software/bsa-acs#48]
The check
https://github.com/ARM-software/bsa-acs/blob/ea487a9965c3c8ab3ec6eeca5856fd9ce568720a/test_pool/peripherals/operating_system/test_os_d005.c#L175
should be changed to
` if ((msr_status & 0xF0) != CTS_DCD_EN) `

**Comment by gowthamsiddarthd** [comment]
HI @hnickvmw,

Thank you for reporting this.
This has been fixed as part of https://github.com/ARM-software/bsa-acs/pull/52

Regards,
Gowtham Siddarth
ACS Team
