### ISSUE TITLE
BSA Linux - Test cases like 863 for RCiEP and i-EP should not be run 

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#57]
This issue is created for BSA Linux for a similar reason to https://github.com/ARM-software/bsa-acs/issues/40.

**Comment by chetan-rathore** [comment]
Hi @sunnywang-arm, 

Can you confirm if the issue is observed with the BSA binary containing  #40 fix. (https://github.com/ARM-software/bsa-acs/pull/51)

Binaries build after 2nd Sep will have the fix.

Regards,
ACS team

**Comment by sunnywang-arm** [comment]
The issue still exists with the image build after 2nd Sep.  As our offline discussion, The root cuase can be that the bsa 863 has actually run for RCiEP device, as 863 doesn't rely on bdf table but linux apis
