### ISSUE TITLE
[pal_uefi_dt][pal_peripherals] Using wrong variable or special purpose?

### ISSUE THREAD

**Issue by thanhhung06** [ARM-software/bsa-acs#69]
Hi ARM's developer,

I'm working with new platform to support Arm System Ready, while running test, I found the strange the source code.
Can you help me explain them?
I expect it use "usb_dt_compatible" instead of "uart_dt_compatible" in L173-L177, or I understand wrong the purpose of those lines?
https://github.com/ARM-software/bsa-acs/blob/main/platform/pal_uefi_dt/src/pal_peripherals.c#L173

Best Regards,
Hung Huynh

**Comment by chetan-rathore** [comment]
Hi @thanhhung06 ,

Changes are merged.

Thanks,
ACS team
