### ISSUE TITLE
BSA wakeup test failure (503, 504, 505) with ES ACS 1.1

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#71]
Use the same system and same firmware to run both ES ACS 1.0 and ES ACS 1.1 BSA wakeup tests, but got a different result. Offline checked with @chetan-rathore. With ES ACS 1.1, it looks like PE is taking some time to enter the WFI state (low-power mode) or not entering it, so caused the failures. Supposedly, PE should enter the WFI state and EL0/EL2 Timers will wake it up. Need to take a further look to check the difference between ES ACS 1.0 and 1.1 and if PE needs more time to enter the WFI state.

ES ACS 1.0 BSA result - All PASS 

```
 503 : Wake from EL0 PHY Timer Int                : Result:  PASS 
 504 : Wake from EL0 VIR Timer Int                : Result:  PASS 
 505 : Wake from EL2 PHY Timer Int                : Result:  PASS 
```
 
ES ACS 1.1 BSA result - All FAIL
```
 503 : Wake from EL0 PHY Timer Int           
       Failed on PE -    0
       Checkpoint --  1                           : Result:  FAIL 
 504 : Wake from EL0 VIR Timer Int           
       Failed on PE -    0
       Checkpoint --  1                           : Result:  FAIL 
 505 : Wake from EL2 PHY Timer Int           
       Failed on PE -    0
       Checkpoint --  1                           : Result:  FAIL 
```

ES ACS 1.1 BSA result (with verbosity INFO message)- All FAIL
```
 503 : Wake from EL0 PHY Timer Int                    START

       Failed on PE -    0
       B_WAK_01, B_WAK_02, B_WAK_03, B_WAK_04, B_WAK_05                     
       B_WAK_06, B_WAK_07, B_WAK_10, B_WAK_11
       Checkpoint --  1                           : Result:  FAIL 
         END

 504 : Wake from EL0 VIR Timer Int                    START

       Failed on PE -    0
       B_WAK_01, B_WAK_02, B_WAK_03, B_WAK_04, B_WAK_05                     
       B_WAK_06, B_WAK_07, B_WAK_10, B_WAK_11
       Checkpoint --  1                           : Result:  FAIL 
         END

 505 : Wake from EL2 PHY Timer Int                    START

       Failed on PE -    0
       B_WAK_01, B_WAK_02, B_WAK_03, B_WAK_04, B_WAK_05                     
       B_WAK_06, B_WAK_07, B_WAK_10, B_WAK_11
       Checkpoint --  1                           : Result:  FAIL 
         END

```

**Comment by chetan-rathore** [comment]
Updates:

On further debug on the system, it is noted that the PE is not entering low-power mode (WFI) which is causing test failures. 
The wakeup tests do expect PE to enter low-power mode and wait for interrupt to wake the PE.

**Comment by chetan-rathore** [comment]
Updates: 
The root cause was related to network link timer running in ATF and with that timer disable, PE is going into low-power state and test behaving as expected
