### ISSUE TITLE
tests 278 and 279 should continue test of all the bdf’s found 

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bsa-acs#84]
278 : Check uniqueness of StreamID 
279 : Check Device's ReqID-DeviceID-StreamID 

For now, if BSA tests 278 and 279 find a problematic device, it will directly return without checking other devices. It looks like we should change the tests to continue to check other devices.

**Comment by rajatgoyal47** [comment]
Hi Sunny,

Thanks for the suggesting this. 
We have made the changes to the code.

Thanks,
Rajat
ACS Team

**Comment by sunnywang-arm** [comment]
Thanks, @rajatgoyal47. Yes, we also verified the changes, so let's close this issue.
