### ISSUE TITLE
Unify test result info like in sbsa-acs?

### ISSUE THREAD

**Issue by hrw** [ARM-software/bsa-acs#93]
SBSA-ACS has val_print_test_end() function to unify output how test block went.

Can you implement it in BSA-ACS too?

https://github.com/ARM-software/sbsa-acs/pull/193

**Comment by chetan-rathore** [comment]
Hi @hrw,

The val_print_test_end function is ported to BSA ACS also.

Thanks,
ACS team

**Comment by chetan-rathore** [comment]
Closing this as changes are merged.
