### ISSUE TITLE
Can test 606 check for 16550 and/or pl011 uart?

### ISSUE THREAD

**Issue by hrw** [ARM-software/bsa-acs#95]
BSA Spec says:

> RB_PER_05 For the purpose of system development and bring up, the base system must include a UART. The UART must be one of:
> • The Generic UART as specified in Section B.
> • A fully 16550 compatible UART

Section B says:

> An instance of the PL011 r1p5 UART will be compliant with this specification.

BSA ACS checks only for 16550 and skips test if it is not present.

**Comment by chetan-rathore** [comment]
Hi @hrw, 

The UART rule B_PER_05 compliance is divided into 2 tests. 

Test 606 (as you also mentioned) is for 16550 UART.
Test 603 is for generic UART (pl011 r1p5)  
https://github.com/ARM-software/bsa-acs/blob/24c9d9814628ee1436a6d49c0934f86a21206910/test_pool/peripherals/operating_system/test_os_d003.c#L27

Thanks,
ACS team
